#!/usr/bin/env bash
set -Eeuo pipefail

# rename-usb-nics-on-pi.sh
#
# Give USB Ethernet adapters stable Linux interface names by MAC address.
# Useful on Raspberry Pi systems where USB NICs may come back as different
# eth/en*/usb names after reboot, especially when libvirt/Cockpit VMs use
# direct/macvtap NIC passthrough.

RULE_FILE="/etc/udev/rules.d/70-rename-usb-nics-on-pi.rules"
MODE="apply"

usage() {
  cat <<'HELP'
Usage:
  sudo ./rename-usb-nics-on-pi.sh [--dry-run] stable-name=mac-address [stable-name=mac-address ...]

Examples:
  sudo ./rename-usb-nics-on-pi.sh \
    usb-lan-a=a0:ce:c8:11:22:33 \
    usb-lan-b=a0:ce:c8:44:55:66

  sudo ./rename-usb-nics-on-pi.sh --dry-run \
    exit-node-a=a0:ce:c8:11:22:33

Find your NIC MAC addresses:
  ip -br link

After applying rules:
  sudo reboot

Verify after reboot:
  ip -br link

Notes:
  - Linux interface names must be 15 characters or fewer.
  - This script overwrites:
      /etc/udev/rules.d/70-rename-usb-nics-on-pi.rules
  - For libvirt/Cockpit VMs using direct/macvtap NICs, update the VM NIC
    source from the old eth/en*/usb name to the new stable name after reboot.
HELP
}

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

validate_name() {
  local name="$1"

  [[ "$name" =~ ^[a-zA-Z0-9_.:-]+$ ]] || fail "Invalid interface name: $name"

  if [[ ${#name} -gt 15 ]]; then
    fail "Interface name too long: $name. Linux interface names must be 15 characters or fewer."
  fi
}

normalize_mac() {
  local mac="${1,,}"

  [[ "$mac" =~ ^([0-9a-f]{2}:){5}[0-9a-f]{2}$ ]] || fail "Invalid MAC address: $1"

  printf '%s\n' "$mac"
}

build_rules() {
  local pair name mac

  echo '# Stable USB NIC names'
  echo '# Generated by rename-usb-nics-on-pi.sh'
  echo '# Edit by rerunning the script with the desired stable-name=mac-address pairs.'
  echo

  for pair in "$@"; do
    [[ "$pair" == *=* ]] || fail "Bad argument: $pair. Use stable-name=mac-address"

    name="${pair%%=*}"
    mac="${pair#*=}"

    [[ -n "$name" ]] || fail "Empty interface name in argument: $pair"
    [[ -n "$mac" ]] || fail "Empty MAC address in argument: $pair"

    validate_name "$name"
    mac="$(normalize_mac "$mac")"

    echo "SUBSYSTEM==\"net\", ACTION==\"add\", ATTR{address}==\"$mac\", NAME=\"$name\""
  done
}

main() {
  local rules

  if [[ $# -lt 1 ]]; then
    usage
    exit 1
  fi

  case "${1:-}" in
    --dry-run)
      MODE="dry-run"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
  esac

  [[ $# -ge 1 ]] || fail "At least one stable-name=mac-address pair is required."

  need_cmd ip
  need_cmd udevadm

  rules="$(build_rules "$@")"

  echo
  echo "Current network links:"
  ip -br link || true

  echo
  echo "Rule file: $RULE_FILE"
  echo
  printf '%s\n' "$rules"

  if [[ "$MODE" == "dry-run" ]]; then
    echo
    echo "Dry run only. No files were changed."
    exit 0
  fi

  [[ $EUID -eq 0 ]] || fail "Run with sudo/root. Example: sudo $0 usb-lan-a=a0:ce:c8:11:22:33"

  install -d -m 0755 "$(dirname "$RULE_FILE")"
  printf '%s\n' "$rules" > "$RULE_FILE"
  chmod 0644 "$RULE_FILE"

  udevadm control --reload-rules

  echo
  echo "Wrote stable NIC rules to:"
  echo "  $RULE_FILE"
  echo
  echo "Next step:"
  echo "  sudo reboot"
  echo
  echo "After reboot verify:"
  echo "  ip -br link"
  echo
  echo "For libvirt/Cockpit VMs using direct/macvtap NICs:"
  echo "  Update the VM NIC source from the old eth/en*/usb name to the new stable name."
}

main "$@"
